"""New Migration

Revision ID: 0ff4fe1d96f6
Revises: 
Create Date: 2023-10-05 21:26:22.240751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff4fe1d96f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ascvd_careplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actions', sa.String(length=500), nullable=True),
    sa.Column('medications', sa.String(length=500), nullable=True),
    sa.Column('rationale', sa.String(length=500), nullable=True),
    sa.Column('recommendations', sa.String(length=500), nullable=True),
    sa.Column('alternatives', sa.String(length=500), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biomarker_careplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actions', sa.String(length=1000), nullable=True),
    sa.Column('medications', sa.String(length=1000), nullable=True),
    sa.Column('rationale', sa.String(length=1000), nullable=True),
    sa.Column('recommendations', sa.String(length=1000), nullable=True),
    sa.Column('alternatives', sa.String(length=1000), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lipid_biomarkers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hdl_c', sa.Float(), nullable=True),
    sa.Column('ldl_c', sa.Float(), nullable=True),
    sa.Column('lp_a', sa.Float(), nullable=True),
    sa.Column('triglycerides', sa.Float(), nullable=True),
    sa.Column('apo_b', sa.Float(), nullable=True),
    sa.Column('apo_a1', sa.Float(), nullable=True),
    sa.Column('hs_crp', sa.Float(), nullable=True),
    sa.Column('units', sa.String(length=10), nullable=True),
    sa.Column('hdl_c_risk', sa.String(length=20), nullable=True),
    sa.Column('ldl_c_risk', sa.String(length=20), nullable=True),
    sa.Column('lp_a_risk', sa.String(length=20), nullable=True),
    sa.Column('triglycerides_risk', sa.String(length=20), nullable=True),
    sa.Column('apo_b_risk', sa.String(length=20), nullable=True),
    sa.Column('apo_a1_risk', sa.String(length=20), nullable=True),
    sa.Column('hs_crp_risk', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ascvd_score', sa.Float(), nullable=True),
    sa.Column('ascvd_risk', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_scores')
    op.drop_table('lipid_biomarkers')
    op.drop_table('biomarker_careplans')
    op.drop_table('ascvd_careplans')
    op.drop_table('patients')
    # ### end Alembic commands ###
